# Generated by Django 3.0.4 on 2020-06-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('register_date', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('group_id', models.IntegerField(null=True)),
                ('friend_num', models.IntegerField(null=True)),
                ('friend_list', models.ManyToManyField(related_name='_user_friend_list_+', to='back_end.User')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('player_num', models.IntegerField(null=True)),
                ('description', models.CharField(default='', max_length=5000)),
                ('truth', models.CharField(default='', max_length=100)),
                ('murder_id', models.IntegerField(null=True)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_end.User')),
                ('history_script_id', models.ManyToManyField(related_name='script_id_history', to='back_end.Script')),
            ],
            options={
                'db_table': 'Script',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('size', models.IntegerField(null=True)),
                ('stage', models.IntegerField(default=0)),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_script', to='back_end.Script')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=20)),
                ('is_murder', models.IntegerField(default=0)),
                ('task', models.CharField(default='', max_length=200)),
                ('background', models.CharField(default='', max_length=200)),
                ('timeline', models.CharField(default='', max_length=200)),
                ('role_description', models.CharField(default='', max_length=5000)),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_script', to='back_end.Script')),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('is_master', models.IntegerField(default=0)),
                ('movement_point', models.IntegerField(default=0)),
                ('ready_1', models.IntegerField(default=0)),
                ('ready_2', models.IntegerField(default=0)),
                ('ready_3', models.IntegerField(default=0)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_role', to='back_end.Role')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_room', to='back_end.Room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_user', to='back_end.User')),
            ],
            options={
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('clue_id', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('clue_description', models.CharField(max_length=5000)),
                ('text', models.CharField(max_length=50)),
                ('player_list', models.ManyToManyField(to='back_end.Player')),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clue_script', to='back_end.Script')),
            ],
            options={
                'db_table': 'Clue',
            },
        ),
    ]
