# Generated by Django 3.0.4 on 2020-05-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_clue',
            fields=[
                ('clue_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('clue_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='game_role',
            fields=[
                ('role_ID', models.DecimalField(decimal_places=0, default=0, max_digits=20, primary_key=True, serialize=False)),
                ('script_ID', models.DecimalField(decimal_places=0, default='', max_digits=20)),
                ('role_name', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=200)),
                ('role_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='game_room',
            fields=[
                ('room_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('size', models.IntegerField(null=True)),
                ('stage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='game_user',
            fields=[
                ('user_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('pass_word', models.CharField(max_length=15)),
                ('remark', models.CharField(max_length=20)),
                ('user_level', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('ready_1', models.IntegerField(default=0)),
                ('ready_2', models.IntegerField(default=0)),
                ('ready_3', models.IntegerField(default=0)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.game_room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.game_user')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('group_id', models.IntegerField(null=True)),
                ('friend_list', models.CharField(max_length=1000, null=True)),
                ('friend_num', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='script',
            fields=[
                ('title', models.CharField(default='', max_length=50)),
                ('script_ID', models.DecimalField(decimal_places=0, default='', max_digits=20, primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('player_num', models.IntegerField(null=True)),
                ('truth', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='None', max_length=5000)),
                ('muder_role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='back_end.game_role')),
            ],
        ),
        migrations.CreateModel(
            name='player_clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField()),
                ('clue_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.game_clue')),
                ('player_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.player')),
                ('room_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.game_room')),
            ],
        ),
        migrations.AddField(
            model_name='game_user',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.User'),
        ),
        migrations.AddField(
            model_name='game_room',
            name='script_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.AddField(
            model_name='game_clue',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
    ]
