# Generated by Django 3.0.5 on 2020-05-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_role',
            fields=[
                ('role_ID', models.DecimalField(decimal_places=0, default=0, max_digits=20, primary_key=True, serialize=False)),
                ('script_ID', models.DecimalField(decimal_places=0, default='', max_digits=20)),
                ('role_name', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=200)),
                ('role_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='script',
            name='script_ID',
            field=models.DecimalField(decimal_places=0, default='', max_digits=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='script',
            name='muder_role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='back_end.game_role'),
        ),
    ]
