# Generated by Django 3.0.4 on 2020-06-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='script_id',
            new_name='script',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='script_id',
            new_name='script',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='author_name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='room',
            name='script_id',
        ),
        migrations.AddField(
            model_name='room',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_script', to='back_end.Script'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='player_list',
            field=models.ManyToManyField(null=True, to='back_end.Player'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_list',
            field=models.ManyToManyField(null=True, related_name='_user_friend_list_+', to='back_end.User'),
        ),
    ]
