# Generated by Django 3.0.5 on 2020-05-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Test',
        ),
    ]
