# Generated by Django 3.0.5 on 2020-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='game_room',
            new_name='game_room1',
        ),
    ]
