# Generated by Django 3.0.5 on 2020-05-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_auto_20200511_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('group_id', models.IntegerField()),
                ('friend_list', models.CharField(max_length=1000)),
                ('friend_num', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
