# Generated by Django 3.0.5 on 2020-05-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_auto_20200511_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_role',
            fields=[
                ('role_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=200)),
                ('role_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='game_room',
            fields=[
                ('room_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('stage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='game_user',
            fields=[
                ('user_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('pass_word', models.CharField(max_length=15)),
                ('remark', models.CharField(max_length=20)),
                ('user_level', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('register_date', models.DateField()),
                ('last_login_time', models.DateTimeField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='script',
            name='id',
        ),
        migrations.RemoveField(
            model_name='script',
            name='name',
        ),
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='script',
            name='script_ID',
            field=models.DecimalField(decimal_places=0, default='', max_digits=20),
        ),
        migrations.AddField(
            model_name='script',
            name='title',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='script',
            name='truth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.game_role')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.game_room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.game_user')),
            ],
        ),
        migrations.AddField(
            model_name='game_room',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.AddField(
            model_name='game_role',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.CreateModel(
            name='game_clue',
            fields=[
                ('clue_ID', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('clue_description', models.CharField(max_length=500)),
                ('script_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script')),
            ],
        ),
    ]
