# Generated by Django 3.0.6 on 2020-05-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_auto_20200511_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='role_id',
        ),
        migrations.AddField(
            model_name='player',
            name='ready_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ready_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ready_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='script',
            name='player_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_clue',
            name='clue_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='game_clue',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.AlterField(
            model_name='game_room',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.AlterField(
            model_name='game_room',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_user',
            name='user_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.game_room'),
        ),
        migrations.AlterField(
            model_name='script',
            name='description',
            field=models.CharField(default='None', max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='game_role',
        ),
        migrations.AddField(
            model_name='player_clue',
            name='clue_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.game_clue'),
        ),
        migrations.AddField(
            model_name='player_clue',
            name='player_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.player'),
        ),
        migrations.AddField(
            model_name='player_clue',
            name='room_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.game_room'),
        ),
    ]
