# Generated by Django 3.0.5 on 2020-05-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0006_auto_20200520_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_clue',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.AlterField(
            model_name='game_room',
            name='script_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.script'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_list',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
